// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGAOy_RHU70HP77-gy53oy507ucCkKIcc',
    appId: '1:1029931053586:web:2b5ea2beb5c4f1f6fbdecb',
    messagingSenderId: '1029931053586',
    projectId: 'eyes-app-d4a89',
    authDomain: 'eyes-app-d4a89.firebaseapp.com',
    storageBucket: 'eyes-app-d4a89.appspot.com',
    measurementId: 'G-0YY1KKS26T',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoxSlBeVnJSXfCFymcuuXfNmZ7CaNGLlY',
    appId: '1:1029931053586:ios:770bbbcecbc93de7fbdecb',
    messagingSenderId: '1029931053586',
    projectId: 'eyes-app-d4a89',
    storageBucket: 'eyes-app-d4a89.appspot.com',
    iosBundleId: 'com.example.congressionalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoxSlBeVnJSXfCFymcuuXfNmZ7CaNGLlY',
    appId: '1:1029931053586:ios:770bbbcecbc93de7fbdecb',
    messagingSenderId: '1029931053586',
    projectId: 'eyes-app-d4a89',
    storageBucket: 'eyes-app-d4a89.appspot.com',
    iosBundleId: 'com.example.congressionalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGAOy_RHU70HP77-gy53oy507ucCkKIcc',
    appId: '1:1029931053586:web:f06ddfbe09a87ea9fbdecb',
    messagingSenderId: '1029931053586',
    projectId: 'eyes-app-d4a89',
    authDomain: 'eyes-app-d4a89.firebaseapp.com',
    storageBucket: 'eyes-app-d4a89.appspot.com',
    measurementId: 'G-RQFWSYH7PL',
  );

}